### ISSUE TITLE
Add instructions for movement. Needs to not be distracting, or in the way of the main screen.

### ISSUE THREAD

**Issue by jacob-and-nathan** [jacob-and-nathan/Javascript-3D-Modeling-Program#4]

**Comment by xinnks** [comment]
Can I take this?

**Comment by xinnks** [comment]
Can I make a suggestion? A couple, actually.

**Comment by jacob-and-nathan** [comment]
Yes that's fine, I have already started it, but the styling could definitely be improved further.

**Comment by xinnks** [comment]
It's one of the things I wanted to comment on. I'd suggest to use consistent colors. The blue and white look fine, you could trow in a dark shade in there too.

**Comment by xinnks** [comment]
Also since you are using plain CSS, I'd suggest to use CSS custom properties to act as variables for your style properties so that you can avoid or at least reduce repetitions.

**Comment by jacob-and-nathan** [comment]
Yes. If the background colour of the `#topMenus` div is the same colour as 'Open Settings Menu -> ' do you think it would look too much like a button?

![Screenshot 2020-04-07 at 11 41 40 AM](https://user-images.githubusercontent.com/48350114/78660363-da52bd00-78c4-11ea-9bc5-44d75c572bfe.png)

**Comment by xinnks** [comment]
Since you wanted it to be non distracting I'd suggest that the background be a shade of black (rgba, some opacity in there) while the text should be a bit to the grey side of white, then on hover is when you have it styled with the blue and white. That way it will be minimally visible (non distracting) while using the app, but on full display on hover.

**Comment by xinnks** [comment]
Something like this:

![hover](https://user-images.githubusercontent.com/8682363/78661709-eac06300-78d7-11ea-855c-dfd451782820.gif)

**Comment by jacob-and-nathan** [comment]
Yep, that's great. Would you like to submit a pull request if you think it's ready?

**Comment by xinnks** [comment]
Sure, let me do that.
